### ISSUE TITLE
Class "Google_Client" not found

### ISSUE THREAD

**Issue by markhowellsmead** [weareferal/craft-remote-backup#64]
I've just installed and configured the plugin but now get the error message _Class "Google_Client" not found_ when loading the settings page (WEBSITE)/admin/settings/plugins/remote-backup.

**Comment by markhowellsmead** [comment]
Running the CLI command returns "Exception 'Error' with message 'Class "Google_Service_Drive_DriveFile" not found'"

**Comment by timmyomahony** [comment]
I believe this is now resolved

**Comment by markhowellsmead** [comment]
This isn't resolved: the GD test connection works, but the backup fails. I've forwarded full details via email.
